### ISSUE TITLE
"default" is imported from external module "react" but never used in "src/file.tsx"

### ISSUE THREAD

**Issue by SlexAxton** [milesj/packemon#232]
I have a file that looks like this:

```tsx
// Avatar.tsx
import {forwardRef} from 'react';
import {avatar, wrapper} from './Avatar.css';
import {createView} from './createView';

interface AvatarProps {
 …
}

function sanitizeString(str = '') {
  …
}

export const Avatar = forwardRef<HTMLSpanElement, AvatarProps>(
  ({avatar, size, variant, badge, ...props}, fwdedRef) => {
    return (
      <StyledAvatarWrapper badge={badge} size={size}>
        <StyledAvatar {...props} ref={fwdedRef} variant={variant}>
          {av}
        </StyledAvatar>
      </StyledAvatarWrapper>
    );
  },
);
```

I have typescript in the root config set with:

```
"jsx": "react-jsx"
```

I can build this without packemon without getting the warning in the title (via rollup or vite or something), but am having trouble finding whichever setting is causing this to happen in packemon.

My invocation in my `moon.yml` file is more or less lifted from the example repo:

```
tasks:
  # https://moonrepo.dev/docs/guides/examples/packemon
  build:
    command:
      - 'packemon'
      - 'pack'
      - '--addEngines'
      - '--addExports'
      - '--declaration'
    inputs:
      - '@globs(sources)'
      - 'package.json'
      - 'tsconfig.*.json'
```

the errors log out twice, presumably once for `tsconfig.esm.json` and once for `tsconfig.lib.json`.

I believe it's happening on every file that has a destructured `react` import like `import {useRef} from 'react';`

Running latest version of `packemon`.

I appreciate the help, just a pointer in a direction works for me if that's all you have time for :pray: .
